import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# -----------------------------
# SMTP CONFIGURATION
# -----------------------------

sender_email = "your_email@gmail.com"
receiver_email = "receiver_email@gmail.com"
password = "your_app_password"

smtp_server = "smtp.gmail.com"
smtp_port = 587

# -----------------------------
# HIGH RISK IOC DATA
# -----------------------------

ioc_ip = "192.168.1.100"
ioc_type = "Malicious IP Address"
risk_level = "HIGH"

# -----------------------------
# EMAIL MESSAGE FORMATTING
# -----------------------------

subject = "🚨 High Risk IOC Detected"

body = f"""
Cybersecurity Alert Notification

IOC Type   : {ioc_type}
IOC Value  : {ioc_ip}
Risk Level : {risk_level}

Action Required Immediately.

Generated By:
TIP Email Alerting System
"""

# -----------------------------
# CREATE EMAIL
# -----------------------------

message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

message.attach(MIMEText(body, "plain"))

# -----------------------------
# SEND EMAIL
# -----------------------------

try:
    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()

    server.login(sender_email, password)

    server.sendmail(
        sender_email,
        receiver_email,
        message.as_string()
    )

    print("✅ Email Alert Sent Successfully")

    with open("alert_log.txt", "a") as log:
        log.write(f"ALERT SENT : {ioc_ip} | {risk_level}\n")

    server.quit()

except Exception as e:
    print("❌ Error Sending Email")
    print(e)

